language: node_js
node_js:
- '6'
os:
- linux
sudo: true
branches:
  except:
    - master
# env:
#   global:

#cache:
#  directories:
#  - node_modules
before_install:
- ./scripts/skip_travis_commits.sh
- sudo add-apt-repository --yes ppa:ubuntu-wine/ppa
- sudo add-apt-repository --yes ppa:arx/release
- sudo apt-get update -d
- sudo apt-get install -y -q innoextract wine python-software-properties
- wine --version
- innoextract --version
- "./scripts/innosetup/innoinstall.sh"
- sudo cp scripts/innosetup/iscc /usr/local/bin/iscc
- iscc /? 2> /dev/null | grep "Inno Setup Preprocessor"
# private keys for app
- if [ "${TRAVIS_SECURE_ENV_VARS}" != "false" ]; then openssl aes-256-cbc -K $encrypted_b624ede0bd8e_key -iv $encrypted_b624ede0bd8e_iv -in private.json.enc -out private.json -d; fi
# install git lfs
#- mkdir -p $HOME/bin
#- wget https://github.com/github/git-lfs/releases/download/v1.3.1/git-lfs-linux-amd64-1.3.1.tar.gz
#- tar xvfz git-lfs-linux-amd64-1.3.1.tar.gz
#- mv git-lfs-1.3.1/git-lfs $HOME/bin/git-lfs
#- export PATH=$PATH:$HOME/bin/
#- rm git-lfs-linux-amd64-1.3.1.tar.gz
before_script:
- git config --global url."https://".insteadOf git://
- npm install
- npm install gulp -g
- npm install bower -g
#- npm install door43-client -g
script: npm test
after_success:
- test $TRAVIS_TEST_RESULT == 0 && $TRAVIS_PULL_REQUEST == "false"
- test -z $TRAVIS_TAG && ./scripts/bump.sh
#- door43-client index -i src/index/index.sqlite -f
- test -f src/index/index.sqlite
#- door43-client download -i src/index/index.sqlite -d src/index/resource_containers -f -c
- test -d src/index/resource_containers
- bower install
# ensure bower installed correctly
- test -d src/components
- gulp prince
# ensure prince was installed
- test -d src/prince
- gulp build --win
- gulp build --linux
- gulp build --osx
- gulp release

deploy:
# develop branch
# - provider: surge
#   project: "./release/"
#   domain: develop.ts-desktop.surge.sh
#   skip_cleanup: true
#   on:
#     branch: develop
#     condition: "-d ./release"
# # catch-all
# - provider: surge
#   project: "./release/"
#   domain: sandbox.ts-desktop.surge.sh
#   skip_cleanup: true
#   on:
#     all_branches: true
#     tags: false
#     condition: "-d ./release && $TRAVIS_BRANCH != develop && ! ($TRAVIS_BRANCH =~ ^release-.*$) && $TRAVIS_BRANCH != master"
# # release branch
# - provider: surge
#   project: "./release/"
#   domain: release.ts-desktop.surge.sh
#   skip_cleanup: true
#   on:
#     all_branches: true
#     tags: false
#     condition: "-d ./release && $TRAVIS_BRANCH =~ ^release-.*$"
# # master branch
- provider: releases
  api_key:
    secure: brjmL3cyCTr6swNCqka2fkc41j+PO2tqXZhE9QyNoDEXcxR1FOwPoPut/8h4N/pISfkf2FibtsWqThhW1Xz1pVNNMBlHRblJsSecfvXOtn7kneCsAV+QBngbPuA8OKzfhXTUeIQNlIpfG+rwlDg28wOthDI/7ADBOYgGQWeOd7o=
  file:
    - release/*.exe
    - release/*.zip
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: unfoldingWord-dev/ts-desktop
    condition: "-d ./release"
